title: Santa Monica Civic Auditorium
baseurl: /civic-auditorium
github_username: thekaveman

#contact info

email: civic@smgov.net
street: 1855 Main Street
city: Santa Monica
state: CA
zip: 90401
map_url: https://www.google.com/maps/place/Santa+Monica+Civic+Auditorium/@34.009085,-118.489339,17z
phone: 310-458-8350
rental_phone: 310-458-4924 

defaults:
  - 
    scope:
      path: ""
    values:
      layout: "page"